# -*- coding: utf-8 -*-
"""Reading data from google sheets using python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gRslbsgQ4T7LPhuTAPOLHjiIeRJaiYnM
"""

from google.colab import auth
auth.authenticate_user()     #Authorizing user
import requests              #Importing request module that allows you to send Http request 
import gspread               #Importing python API for google sheets
from oauth2client.client import GoogleCredentials
gc = gspread.authorize(GoogleCredentials.get_application_default())

import pandas as pd                #Importing pandas
sheetname = "IU1841050026"         #Enter the file name without extension
sh = gc. open(sheetname)           
worksheet = sh.sheet1              #Using API for opening sheet
values_list = worksheet.get_all_values()      #Extracting all values from sheet
df = pd.DataFrame(values_list)                
df.head()

